package ir.puyaars.plantsapp.repository.entities;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

import java.util.List;

import androidx.room.Entity;
import androidx.room.PrimaryKey;

@Entity(tableName = "plants")
public class PlantEntity {

    /**
     * json schema of Plant object
     * {
     *   "name": "",
     *   "nameRoot": "",
     *   "commonName": "",
     *   "image": "",
     *   "enName": "",
     *   "siName": "",
     *   "family": "",
     *   "identity": "",
     *   "herbals": "",
     *   "specs": [
     *     {"title":"",
     *      "desc":""}
     *   ]
     * }
     *
     * id is auto generated by database
     * favourite is defaulted on false
     *
     * used Builder class for plant definition
     */

    @PrimaryKey(autoGenerate = true)
    private int id;
    @SerializedName("name")
    @Expose
    private String name;
    @SerializedName("nameRoot")
    @Expose
    private String nameRoot;
    @SerializedName("commonName")
    @Expose
    private String commonName;
    @SerializedName("image")
    @Expose
    private String image;
    @SerializedName("enName")
    @Expose
    private String enName;
    @SerializedName("siName")
    @Expose
    private String siName;
    @SerializedName("family")
    @Expose
    private String family;
    @SerializedName("identity")
    @Expose
    private String identity;
    @SerializedName("specs")
    @Expose
    private List<Spec> specs;
    @SerializedName("herbals")
    @Expose
    private String herbals;
    private boolean favourite;

    public PlantEntity(int id, String name, String nameRoot, String commonName, String image, String enName, String siName, String family, String identity, List<Spec> specs, String herbals) {
        this.id = id;
        this.name = name;
        this.nameRoot = nameRoot;
        this.commonName = commonName;
        this.image = image;
        this.enName = enName;
        this.siName = siName;
        this.family = family;
        this.identity = identity;
        this.specs = specs;
        this.herbals = herbals;
        this.favourite = false;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getNameRoot() {
        return nameRoot;
    }

    public void setNameRoot(String nameRoot) {
        this.nameRoot = nameRoot;
    }

    public String getCommonName() {
        return commonName;
    }

    public void setCommonName(String commonName) {
        this.commonName = commonName;
    }

    public String getEnName() {
        return enName;
    }

    public void setEnName(String enName) {
        this.enName = enName;
    }

    public String getSiName() {
        return siName;
    }

    public void setSiName(String siName) {
        this.siName = siName;
    }

    public String getFamily() {
        return family;
    }

    public void setFamily(String family) {
        this.family = family;
    }

    public String getIdentity() {
        return identity;
    }

    public void setIdentity(String identity) {
        this.identity = identity;
    }

    public List<Spec> getSpecs() {
        return specs;
    }

    public void setSpecs(List<Spec> specs) {
        this.specs = specs;
    }

    public String getHerbals() {
        return herbals;
    }

    public void setHerbals(String herbals) {
        this.herbals = herbals;
    }

    public boolean isFavourite() {
        return favourite;
    }

    public void setFavourite(boolean favourite) {
        this.favourite = favourite;
    }

    public static class Builder {
        private int id;
        private String name;
        private String nameRoot;
        private String commonName;
        private String image;
        private String enName;
        private String siName;
        private String family;
        private String identity;
        private List<Spec> specs;
        private String herbals;

        public Builder() {
        }

        public static Builder plantEntity() {
            return new Builder();
        }

        public Builder withId(int id) {
            this.id = id;
            return this;
        }

        public Builder withName(String name) {
            this.name = name;
            return this;
        }

        public Builder withNameRoot(String nameRoot) {
            this.nameRoot = nameRoot;
            return this;
        }

        public Builder withCommonName(String commonName) {
            this.commonName = commonName;
            return this;
        }

        public Builder withImage(String image) {
            this.image = image;
            return this;
        }

        public Builder withEnName(String enName) {
            this.enName = enName;
            return this;
        }

        public Builder withSiName(String siName) {
            this.siName = siName;
            return this;
        }

        public Builder withFamily(String family) {
            this.family = family;
            return this;
        }

        public Builder withIdentity(String identity) {
            this.identity = identity;
            return this;
        }

        public Builder withSpecs(List<Spec> specs) {
            this.specs = specs;
            return this;
        }

        public Builder withHerbals(String herbals) {
            this.herbals = herbals;
            return this;
        }

        public PlantEntity build() {
            return new PlantEntity(id,name,nameRoot,commonName, image, enName,siName,family,identity,specs,herbals);
        }
    }
}
